# Copyright The Cloud Custodian Authors.
# SPDX-License-Identifier: Apache-2.0

ResourceMap = {
    "huaweicloud.lts-transfer": "c7n_huaweicloud.resources.transfer.Transfer",
    "huaweicloud.evs-volume": "c7n_huaweicloud.resources.evs.Volume",
    "huaweicloud.er": "c7n_huaweicloud.resources.er.ERInstance",
    "huaweicloud.deh": "c7n_huaweicloud.resources.deh.Deh",
    "huaweicloud.config-tracker": "c7n_huaweicloud.resources.config.ConfigTracker",
    "huaweicloud.obs": "c7n_huaweicloud.resources.obs.Obs",
    "huaweicloud.ces-alarm": "c7n_huaweicloud.resources.ces.Alarm",
    "huaweicloud.kms": "c7n_huaweicloud.resources.kms.Kms",
    "huaweicloud.ecs": "c7n_huaweicloud.resources.ecs.Ecs",
    "huaweicloud.bms": "c7n_huaweicloud.resources.bms.Bms",
    "huaweicloud.iam-user": "c7n_huaweicloud.resources.iam.User",
    "huaweicloud.iam-policy": "c7n_huaweicloud.resources.iam.Policy",
    "huaweicloud.vpc": "c7n_huaweicloud.resources.vpc.Vpc",
    "huaweicloud.vpc-flow-log": "c7n_huaweicloud.resources.vpc.FlowLog",
    "huaweicloud.vpc-peering": "c7n_huaweicloud.resources.vpc.Peering",
    "huaweicloud.vpc-port": "c7n_huaweicloud.resources.vpc.Port",
    "huaweicloud.vpc-security-group": "c7n_huaweicloud.resources.vpc.SecurityGroup",
    "huaweicloud.vpc-security-group-rule": "c7n_huaweicloud.resources.vpc.SecurityGroupRule",
    "huaweicloud.functiongraph": "c7n_huaweicloud.resources.functiongraph.FunctionGraph",
    "huaweicloud.elb-loadbalancer": "c7n_huaweicloud.resources.elb.Loadbalancer",
    "huaweicloud.ims": "c7n_huaweicloud.resources.ims.Ims",
    "huaweicloud.smn-topic": "c7n_huaweicloud.resources.smn.Topic",
    "huaweicloud.elb-listener": "c7n_huaweicloud.resources.elb.Listener",
    "huaweicloud.nat-gateway": "c7n_huaweicloud.resources.nat.NatGateway",
    "huaweicloud.nat-snat-rule": "c7n_huaweicloud.resources.nat.NatSnatRule",
    "huaweicloud.nat-dnat-rule": "c7n_huaweicloud.resources.nat.NatDnatRule",
    "huaweicloud.secmaster": "c7n_huaweicloud.resources.secmaster.Secmaster",
    "huaweicloud.hss": "c7n_huaweicloud.resources.hss.Hss",
    "huaweicloud.cts-tracker": "c7n_huaweicloud.resources.cts-tracker.Tracker",
    "huaweicloud.cts-notification-smn":
        "c7n_huaweicloud.resources.cts-notification-smn.Notification",
    "huaweicloud.cts-notification-func":
        "c7n_huaweicloud.resources.cts-notification-func.Notification",
    "huaweicloud.cbr-backup": "c7n_huaweicloud.resources.cbr_backup.CbrBackup",
    "huaweicloud.cbr-vault": "c7n_huaweicloud.resources.cbr_vault.CbrVault",
    "huaweicloud.sfsturbo": "c7n_huaweicloud.resources.sfsturbo.SfsTurbo",
    "huaweicloud.coc": "c7n_huaweicloud.resources.coc.Coc",
    "huaweicloud.org-policy": "c7n_huaweicloud.resources.organizations.OrgPolicy",
    "huaweicloud.org-account": "c7n_huaweicloud.resources.organizations.OrgAccount",
    "huaweicloud.org-unit": "c7n_huaweicloud.resources.organizations.OrgUnit",
    "huaweicloud.ram-shared-principals": "c7n_huaweicloud.resources.ram.RAMSharedPrincipals",
    "huaweicloud.antiddos-eip": "c7n_huaweicloud.resources.antiddos.Eip",
    "huaweicloud.kafka": "c7n_huaweicloud.resources.kafka.Kafka",
    "huaweicloud.apig-api": "c7n_huaweicloud.resources.apig.ApiResource",
    "huaweicloud.apig-stage": "c7n_huaweicloud.resources.apig.StageResource",
    "huaweicloud.apig-api-groups": "c7n_huaweicloud.resources.apig.ApiGroupResource",
    "huaweicloud.reliability": "c7n_huaweicloud.resources.rocketmq.RocketMQ",
    "huaweicloud.dc": "c7n_huaweicloud.resources.dc.DC",
    "huaweicloud.scm": "c7n_huaweicloud.resources.scm.Scm",
    "huaweicloud.swr": "c7n_huaweicloud.resources.swr.Swr",
    "huaweicloud.swr-image": "c7n_huaweicloud.resources.swr.SwrImage",
    "huaweicloud.eip": "c7n_huaweicloud.resources.eip.EIP",
    "huaweicloud.cc-cloud-connection": "c7n_huaweicloud.resources.cc.CloudConnection",
    "huaweicloud.cdn-domain": "c7n_huaweicloud.resources.cdn.CdnDomain",
    "huaweicloud.rds": "c7n_huaweicloud.resources.rds.RDS",
    "huaweicloud.aom-alarm": "c7n_huaweicloud.resources.aom.AomAlarm",
    "huaweicloud.eg-subscription": "c7n_huaweicloud.resources.eg.Subscription",
    "huaweicloud.workspace-desktop": "c7n_huaweicloud.resources.workspace.Workspace"
}
